/**
 * npm run assets:list: writes ASSETS_NEEDED.md, the art checklist. It lists every art slot with
 * its file name, size and a drawing idea, marks the ones already in assets/art/, and flags
 * uploads with the wrong size or an unknown name.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ART_CATEGORY_TEXT, ART_SIZES, ART_SLOTS, type ArtCategory } from '../../src/content/art';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const artDir = join(root, 'assets', 'art');
mkdirSync(artDir, { recursive: true });

/** Width and height from a PNG header (bytes 16–23 of the IHDR chunk). */
function pngSize(path: string): { w: number; h: number } | null {
  const b = readFileSync(path);
  if (b.length < 24 || b.toString('ascii', 1, 4) !== 'PNG') return null;
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

const files = new Set(readdirSync(artDir).filter((f) => f.toLowerCase().endsWith('.png')));
const known = new Set(ART_SLOTS.map((s) => s.file));
const order: ArtCategory[] = [
  'cartridge',
  'memo',
  'voucher',
  'analyst',
  'tag',
  'page',
  'review',
  'desk',
  'client',
  'family',
  'cardback',
  'achievement',
];

const lines: string[] = [];
const done = ART_SLOTS.filter((s) => files.has(s.file)).length;
lines.push(
  '# Art checklist',
  '',
  `**${done} of ${ART_SLOTS.length} uploaded.** This file is generated by \`npm run assets:list\`; don't edit it by hand.`,
  '',
  '## How to upload (no coding)',
  '',
  '1. Open the repository on github.com and switch to the branch `claude/game-build-phases-dkpsed` (the branch drop-down near the top left).',
  '2. Click into the folder `assets` → `art`.',
  '3. Click **Add file → Upload files**, then drag in your PNGs (as many at once as you like).',
  '4. Scroll down and click **Commit changes**.',
  '5. Tell Claude Code "I uploaded art". It rebuilds the game, and every picture appears where it belongs.',
  '',
  '## The rules for every picture',
  '',
  '- **PNG with a transparent background**, pixel art, **exactly the size listed** for its section. The game scales it up by whole numbers, so pixels stay crisp.',
  '- **Name the file exactly as listed** (all lowercase, e.g. `cartridge-theta_engine.png`). A misspelled name is simply ignored.',
  '- **No frame, no text, no rarity color**: the game draws the card frame, the name and the rarity around your picture.',
  "- **Palette:** deep indigo and black, with neon cyan (#3ef2ff), magenta (#ff3ea5) and amber (#ffbf3e) accents. Keep outlines dark so the icon reads on the game's dark cards.",
  '- **Original art only** (yours, commissioned, or CC0). Nothing traced from Balatro or other games.',
  "- Anything not uploaded shows a placeholder tile with the item's initials, so upload in any order.",
  '',
  '## Summary',
  '',
  '| Section | Size (px) | Uploaded | Priority |',
  '|---|---|---|---|',
  ...order.map((c) => {
    const all = ART_SLOTS.filter((s) => s.category === c);
    const have = all.filter((s) => files.has(s.file)).length;
    const sz = ART_SIZES[c];
    return `| ${ART_CATEGORY_TEXT[c].title} | ${sz.w} × ${sz.h} | ${have} / ${all.length} | ${ART_CATEGORY_TEXT[c].priority === 1 ? '**1 (first)**' : ART_CATEGORY_TEXT[c].priority === 2 ? '2' : '3 (nice to have)'} |`;
  }),
  '',
);

const problems: string[] = [];
for (const f of files) {
  if (!known.has(f)) problems.push(`- \`${f}\` doesn't match any slot name (check the spelling).`);
  else {
    const slot = ART_SLOTS.find((s) => s.file === f)!;
    const sz = pngSize(join(artDir, f));
    const want = ART_SIZES[slot.category];
    if (!sz) problems.push(`- \`${f}\` isn't a valid PNG.`);
    else if (sz.w !== want.w || sz.h !== want.h)
      problems.push(`- \`${f}\` is ${sz.w} × ${sz.h}; it should be ${want.w} × ${want.h}.`);
  }
}
if (problems.length) lines.push('## Problems with uploads', '', ...problems, '');

for (const c of order) {
  const t = ART_CATEGORY_TEXT[c];
  const sz = ART_SIZES[c];
  lines.push(
    `## ${t.title}`,
    '',
    `**${sz.w} × ${sz.h} px.** Shown on: ${t.where}.`,
    '',
    '| ✓ | File name | Item | What it does | Drawing idea |',
    '|---|---|---|---|---|',
  );
  for (const s of ART_SLOTS.filter((x) => x.category === c)) {
    const cell = (x: string) => x.replace(/\|/g, '/').replace(/\n/g, ' ');
    lines.push(
      `| ${files.has(s.file) ? '✅' : '⬜'} | \`${s.file}\` | ${cell(s.name)} | ${cell(s.what)} | ${cell(s.idea)} |`,
    );
  }
  lines.push('');
}

writeFileSync(join(root, 'ASSETS_NEEDED.md'), lines.join('\n'));
if (!existsSync(join(artDir, 'README.md')))
  writeFileSync(
    join(artDir, 'README.md'),
    '# Game art\n\nUpload PNGs here, named exactly as listed in `ASSETS_NEEDED.md` at the top of the repository.\n',
  );
console.log(
  `ASSETS_NEEDED.md: ${done}/${ART_SLOTS.length} uploaded${problems.length ? `, ${problems.length} problem(s)` : ''}.`,
);
