import type { EarningsTiming, SizeTier } from '../types';

/**
 * The SIM market: fictional companies with invented price histories. Used when the real
 * database has not been built yet, in tests, in the balance simulator, and for the
 * "synthetic markets" setting. Every screen labels it SIM.
 */
export interface SynthSpec {
  symbol: string;
  name: string;
  sector: string;
  sizeTier: SizeTier;
  isEtf: boolean;
  weeklies: boolean;
  price0: number;
  drift: number; // annual
  beta: number;
  idioVol: number; // annual long-run idiosyncratic vol
  vrp: number; // implied / realized vol ratio (the premium sellers harvest)
  earnMove: number; // sd of the earnings-day log move (0 for ETFs)
  earnMonth: number; // 0,1,2: which month of each quarter they report in
  earnDay: number;
  timing: EarningsTiming;
  divYield: number;
  skew: number; // IV slope per standardized moneyness unit (negative = put skew)
  smile: number;
  spreadFactor: number; // bid/ask width multiplier (1 = average)
  split?: { date: string; ratio: number };
  reason: string;
}

export const SYNTH_UNIVERSE: SynthSpec[] = [
  {
    symbol: 'MKTX',
    name: 'Broad Market Trust',
    sector: 'Index ETF',
    sizeTier: 'etf',
    isEtf: true,
    weeklies: true,
    price0: 268,
    drift: 0.09,
    beta: 1,
    idioVol: 0.015,
    vrp: 1.18,
    earnMove: 0,
    earnMonth: 0,
    earnDay: 1,
    timing: 'UNK',
    divYield: 0.014,
    skew: -0.2,
    smile: 0.035,
    spreadFactor: 0.3,
    reason: 'SIM benchmark (stands in for SPY)',
  },
  {
    symbol: 'INDX',
    name: 'Thirty Industrials Trust',
    sector: 'Index ETF',
    sizeTier: 'etf',
    isEtf: true,
    weeklies: true,
    price0: 248,
    drift: 0.07,
    beta: 0.92,
    idioVol: 0.04,
    vrp: 1.15,
    earnMove: 0,
    earnMonth: 0,
    earnDay: 1,
    timing: 'UNK',
    divYield: 0.017,
    skew: -0.18,
    smile: 0.03,
    spreadFactor: 0.6,
    reason: 'SIM market context (stands in for DIA)',
  },
  {
    symbol: 'HLXR',
    name: 'Helix Robotics',
    sector: 'Technology',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 158,
    drift: 0.12,
    beta: 1.15,
    idioVol: 0.19,
    vrp: 1.12,
    earnMove: 0.045,
    earnMonth: 0,
    earnDay: 29,
    timing: 'AMC',
    divYield: 0.005,
    skew: -0.11,
    smile: 0.03,
    spreadFactor: 0.45,
    reason: 'Mega-cap tech, tight markets',
  },
  {
    symbol: 'NMBC',
    name: 'Nimbus Cloud Systems',
    sector: 'Technology',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 94,
    drift: 0.12,
    beta: 1.05,
    idioVol: 0.18,
    vrp: 1.1,
    earnMove: 0.05,
    earnMonth: 0,
    earnDay: 24,
    timing: 'AMC',
    divYield: 0.008,
    skew: -0.1,
    smile: 0.03,
    spreadFactor: 0.5,
    reason: 'Mega-cap software',
  },
  {
    symbol: 'QSLC',
    name: 'Quanta Silicon',
    sector: 'Semiconductors',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 212,
    drift: 0.15,
    beta: 1.55,
    idioVol: 0.36,
    vrp: 1.1,
    earnMove: 0.08,
    earnMonth: 1,
    earnDay: 21,
    timing: 'AMC',
    divYield: 0.001,
    skew: -0.07,
    smile: 0.035,
    spreadFactor: 0.6,
    split: { date: '2021-07-20', ratio: 4 },
    reason: 'High-beta chip name',
  },
  {
    symbol: 'ORGR',
    name: 'Orbital Grocers',
    sector: 'Consumer Staples',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 176,
    drift: 0.06,
    beta: 0.6,
    idioVol: 0.14,
    vrp: 1.14,
    earnMove: 0.035,
    earnMonth: 1,
    earnDay: 16,
    timing: 'BMO',
    divYield: 0.022,
    skew: -0.12,
    smile: 0.025,
    spreadFactor: 0.8,
    reason: 'Low-vol dividend payer',
  },
  {
    symbol: 'SOLX',
    name: 'Solace Therapeutics',
    sector: 'Healthcare',
    sizeTier: 'mid',
    isEtf: false,
    weeklies: true,
    price0: 61,
    drift: 0.02,
    beta: 0.8,
    idioVol: 0.42,
    vrp: 1.08,
    earnMove: 0.12,
    earnMonth: 1,
    earnDay: 6,
    timing: 'BMO',
    divYield: 0,
    skew: -0.05,
    smile: 0.05,
    spreadFactor: 1.4,
    reason: 'Biotech: big binary earnings',
  },
  {
    symbol: 'FRTL',
    name: 'Freightline Logistics',
    sector: 'Industrials',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 118,
    drift: 0.07,
    beta: 1.05,
    idioVol: 0.22,
    vrp: 1.12,
    earnMove: 0.06,
    earnMonth: 0,
    earnDay: 20,
    timing: 'BMO',
    divYield: 0.012,
    skew: -0.11,
    smile: 0.03,
    spreadFactor: 0.9,
    reason: 'Cyclical industrial',
  },
  {
    symbol: 'BNKR',
    name: 'Bunker Bancorp',
    sector: 'Financials',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 108,
    drift: 0.08,
    beta: 1.15,
    idioVol: 0.18,
    vrp: 1.13,
    earnMove: 0.035,
    earnMonth: 0,
    earnDay: 14,
    timing: 'BMO',
    divYield: 0.028,
    skew: -0.13,
    smile: 0.03,
    spreadFactor: 0.55,
    reason: 'Money-center bank',
  },
  {
    symbol: 'PLSM',
    name: 'Plasma Motors',
    sector: 'Autos',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 62,
    drift: 0.1,
    beta: 1.9,
    idioVol: 0.55,
    vrp: 1.05,
    earnMove: 0.1,
    earnMonth: 0,
    earnDay: 25,
    timing: 'AMC',
    divYield: 0,
    skew: -0.02,
    smile: 0.04,
    spreadFactor: 0.55,
    reason: 'High-IV mega-cap EV maker',
  },
  {
    symbol: 'MEMX',
    name: 'MemeStonk Arcade',
    sector: 'Retail',
    sizeTier: 'mid',
    isEtf: false,
    weeklies: true,
    price0: 18,
    drift: 0.0,
    beta: 1.4,
    idioVol: 0.85,
    vrp: 1.05,
    earnMove: 0.15,
    earnMonth: 2,
    earnDay: 10,
    timing: 'AMC',
    divYield: 0,
    skew: 0.02,
    smile: 0.06,
    spreadFactor: 1.8,
    reason: 'Meme stock: wild IV, wide markets',
  },
  {
    symbol: 'CRYP',
    name: 'Cryptic Exchange',
    sector: 'Financials',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 46,
    drift: 0.04,
    beta: 1.8,
    idioVol: 0.72,
    vrp: 1.06,
    earnMove: 0.12,
    earnMonth: 1,
    earnDay: 3,
    timing: 'AMC',
    divYield: 0,
    skew: -0.02,
    smile: 0.05,
    spreadFactor: 1.3,
    reason: 'Crypto broker: high IV',
  },
  {
    symbol: 'STRM',
    name: 'Streamline Media',
    sector: 'Communication',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 305,
    drift: 0.08,
    beta: 1.1,
    idioVol: 0.29,
    vrp: 1.1,
    earnMove: 0.09,
    earnMonth: 0,
    earnDay: 18,
    timing: 'AMC',
    divYield: 0,
    skew: -0.08,
    smile: 0.035,
    spreadFactor: 0.6,
    reason: 'Streaming giant: big earnings gaps',
  },
  {
    symbol: 'PXLD',
    name: 'Pixeldust Games',
    sector: 'Communication',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 128,
    drift: 0.06,
    beta: 1.2,
    idioVol: 0.3,
    vrp: 1.1,
    earnMove: 0.08,
    earnMonth: 1,
    earnDay: 8,
    timing: 'AMC',
    divYield: 0,
    skew: -0.08,
    smile: 0.035,
    spreadFactor: 0.9,
    reason: 'Game publisher',
  },
  {
    symbol: 'GRDN',
    name: 'Gridiron Energy',
    sector: 'Energy',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 71,
    drift: 0.05,
    beta: 0.9,
    idioVol: 0.28,
    vrp: 1.12,
    earnMove: 0.04,
    earnMonth: 0,
    earnDay: 28,
    timing: 'BMO',
    divYield: 0.035,
    skew: -0.1,
    smile: 0.03,
    spreadFactor: 0.8,
    reason: 'Oil major, dividend',
  },
  {
    symbol: 'LUXE',
    name: 'Luxe Warehouse Club',
    sector: 'Consumer Staples',
    sizeTier: 'mega',
    isEtf: false,
    weeklies: true,
    price0: 296,
    drift: 0.1,
    beta: 0.75,
    idioVol: 0.16,
    vrp: 1.12,
    earnMove: 0.04,
    earnMonth: 2,
    earnDay: 5,
    timing: 'AMC',
    divYield: 0.007,
    skew: -0.12,
    smile: 0.025,
    spreadFactor: 0.6,
    reason: 'Steady mega-cap retailer',
  },
  {
    symbol: 'AVNR',
    name: 'Avionaire Aerospace',
    sector: 'Industrials',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 205,
    drift: 0.04,
    beta: 1.2,
    idioVol: 0.3,
    vrp: 1.1,
    earnMove: 0.06,
    earnMonth: 0,
    earnDay: 26,
    timing: 'BMO',
    divYield: 0.01,
    skew: -0.1,
    smile: 0.03,
    spreadFactor: 0.8,
    reason: 'Aerospace with headline risk',
  },
  {
    symbol: 'DSKT',
    name: 'Desktop Dynamics',
    sector: 'Technology',
    sizeTier: 'large',
    isEtf: false,
    weeklies: true,
    price0: 238,
    drift: 0.08,
    beta: 1.25,
    idioVol: 0.3,
    vrp: 1.1,
    earnMove: 0.09,
    earnMonth: 2,
    earnDay: 1,
    timing: 'AMC',
    divYield: 0,
    skew: -0.08,
    smile: 0.035,
    spreadFactor: 0.8,
    reason: 'SaaS with big post-earnings moves',
  },
];

export const SYNTH_BENCHMARK = 'MKTX';
export const SYNTH_CONTEXT = ['MKTX', 'INDX'];
export const SYNTH_FIRST_BAR = '2018-01-02';
export const SYNTH_FIRST_CHAIN = '2019-02-01';
export const SYNTH_LAST_DATE = '2026-09-25';
export const SYNTH_SEED = 'stg-sim-v1';
