import type { TradeFacts } from '../../src/content/types';
import { emptyFamilies } from '../../src/content/families';
import type { PipelineInput } from '../../src/engine/run/score';
import type { RunConfig } from '../../src/engine/run/types';
import { DEFAULT_REALISM, defaultPause } from '../../src/engine/lifecycle/daily';

export const cfg: RunConfig = {
  seed: 'u',
  deskId: 'verticals',
  mode: 'career',
  tier: 0,
  startEquityCents: 500_000,
  pureMarket: false,
  realism: { ...DEFAULT_REALISM },
  pause: defaultPause(),
  callMode: 'em',
  rescale: true,
  quarters: 4,
  benchmark: null,
  startingStress: 0,
  extraRerolls: 0,
  practice: false,
};

export function facts(over: Partial<TradeFacts> = {}): TradeFacts {
  return {
    positionId: 'p1',
    cardId: 'c1',
    structureId: 'bull_put',
    family: 'vertical',
    bias: 'bull',
    win: true,
    realizedCents: 10_000, // +2% of $5,000 = 200 chips
    riskPct: 0.05,
    shortPremium: true,
    credit: true,
    creditOfWidth: 0.34,
    pctOfMaxProfit: 0.6,
    returnOnRisk: 0.2,
    closedAtPlan: null,
    exitReason: 'manual',
    expiredWorthless: false,
    dteAtEntry: 30,
    dteAtClose: 15,
    daysOpen: 10,
    daysInProfit: 6,
    heldOverWeekend: true,
    ivrAtEntry: 40,
    ivChangePct: -0.1,
    ivMinusHvAtEntry: 2,
    heldThroughEarnings: false,
    moveVsEm: 0.3,
    stayedInsideEm: true,
    rsiAtEntry: 50,
    shortOutsideBollinger: false,
    macdCrossWithin2: false,
    trendAligned: true,
    counterTrend: false,
    against5dTrend: false,
    callExact: false,
    callAdjacent: false,
    callDirectionRight: false,
    callBucket: 3,
    callActual: 2,
    callBigBucket: false,
    callFlat: false,
    rollsForCredit: 0,
    closedDayAfterMacro: false,
    eventDayWin: false,
    assigned: false,
    cspAssigned: false,
    coveredCallDividend: false,
    coveredCallExpiredOtm: false,
    pinnedFly: false,
    straddleBeatEm: false,
    condorOutsideEm: false,
    gappedThroughShort: false,
    earningsMoveRatio: null,
    highIv: false,
    portfolioDeltaAtClose: 0,
    frontIvAboveBack: null,
    isDoubleCalendar: false,
    diagonalWithTrend: false,
    thetaChips: 0,
    callBonus: 0,
    stopDeclined: false,
    noStop: false,
    lossWithinStop: false,
    dividendsCollected: 0,
    longPremiumThroughEvent: false,
    debitDirectional: false,
    ivCrushWin: false,
    straddlesBefore: 0,
    isStraddle: false,
    shortDte: 15,
    ...over,
  };
}

export function pipe(over: Partial<PipelineInput> = {}): PipelineInput {
  return {
    facts: facts(),
    deskId: 'verticals',
    level: 1,
    goodRR: false,
    edgeTier: null,
    reviewId: null,
    families: emptyFamilies(),
    cartridges: [],
    cartState: {},
    run: {
      quarter: 1,
      roundIndex: 0,
      reviewId: null,
      deskId: 'verticals',
      families: emptyFamilies(),
      ownedCartridges: [],
      patienceStacks: 0,
      rollArtistStacks: 0,
      deltaNeutralOk: true,
      gapInsuranceUsed: false,
      ghostScore: 100,
    },
    doubleDown: false,
    hedge: false,
    ...over,
  };
}
